spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowed-headers: "*"
            allow-credentials: true
        add-to-simple-url-handler-mapping: true
      routes:
      - id: CustomerService
        uri: ${CUSTOMER-SERVICE}
        predicates:
        - Path=/user/**
      - id: ProductService
        uri: ${PRODUCT-SERVICE}
        predicates:
        - Path=/product/**
      httpclient:
        ssl:
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0

  jpa:
    open-in-view: false


server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  port: 8590

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,caches,loggers,info

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50

# Rate Limiter Configuration
  ratelimiter:
    configs:
      default:
        limitForPeriod: 7
        limit-refresh-period:
          seconds: 1

logging:
  level:
    root: warn